services:
  postgres:
    image: postgres:16-alpine
    container_name: aarogya-db
    environment:
      POSTGRES_DB: aarogya_ehr
      POSTGRES_USER: aarogya
      POSTGRES_PASSWORD: aarogya
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aarogya -d aarogya_ehr"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
