export interface IndicatorDefinition {
  id: string;
  name: string;
  category: string;
  nabhStandard: string;
  description: string;
  numeratorDesc: string;
  denominatorDesc: string;
  targetRate?: number;
  computationType: "auto" | "manual" | "semi";
  dataSource: string;
}

export const NABH_INDICATOR_DEFINITIONS: IndicatorDefinition[] = [
  // ── Clinical ──────────────────────────────────────────────────────────
  {
    id: "MED_ERROR_RATE",
    name: "Medication Error Rate",
    category: "Clinical",
    nabhStandard: "COP-5",
    description: "Percentage of prescriptions with medication errors",
    numeratorDesc: "Number of prescriptions with errors",
    denominatorDesc: "Total number of prescriptions",
    targetRate: 2.0,
    computationType: "auto",
    dataSource: "prescriptions",
  },
  {
    id: "AVG_LOS",
    name: "Average Length of Stay",
    category: "Clinical",
    nabhStandard: "COP-7",
    description: "Average duration of inpatient stays in days",
    numeratorDesc: "Total inpatient days",
    denominatorDesc: "Number of discharges",
    computationType: "auto",
    dataSource: "encounters",
  },
  {
    id: "C_SECTION_RATE",
    name: "C-Section Rate",
    category: "Clinical",
    nabhStandard: "COP-8",
    description: "Percentage of deliveries performed via C-section",
    numeratorDesc: "Number of C-section deliveries",
    denominatorDesc: "Total number of deliveries",
    targetRate: 25.0,
    computationType: "auto",
    dataSource: "encounters+obgyn_records",
  },
  {
    id: "READMISSION_RATE",
    name: "Unplanned Readmission Rate (30-day)",
    category: "Clinical",
    nabhStandard: "COP-9",
    description: "Percentage of patients readmitted within 30 days of discharge",
    numeratorDesc: "Number of unplanned readmissions within 30 days",
    denominatorDesc: "Total number of discharges",
    targetRate: 10.0,
    computationType: "auto",
    dataSource: "encounters",
  },

  // ── Infection Control ─────────────────────────────────────────────────
  {
    id: "CAUTI_RATE",
    name: "CAUTI Rate",
    category: "Infection Control",
    nabhStandard: "PCI-2",
    description: "Catheter-Associated Urinary Tract Infection rate per 1,000 catheter-days",
    numeratorDesc: "Number of CAUTI cases",
    denominatorDesc: "Total catheter-days (×1000)",
    targetRate: 5.0,
    computationType: "semi",
    dataSource: "diagnoses (ICD codes N10, N30.0, N39.0)",
  },
  {
    id: "VAP_RATE",
    name: "VAP Rate",
    category: "Infection Control",
    nabhStandard: "PCI-2",
    description: "Ventilator-Associated Pneumonia rate per 1,000 ventilator-days",
    numeratorDesc: "Number of VAP cases",
    denominatorDesc: "Total ventilator-days (×1000)",
    targetRate: 5.0,
    computationType: "semi",
    dataSource: "diagnoses (ICD codes J15-J18 with ventilator)",
  },
  {
    id: "SSI_RATE",
    name: "Surgical Site Infection Rate",
    category: "Infection Control",
    nabhStandard: "PCI-3",
    description: "Percentage of surgical procedures with post-op SSI",
    numeratorDesc: "Number of SSI cases",
    denominatorDesc: "Number of surgical procedures",
    targetRate: 2.0,
    computationType: "auto",
    dataSource: "diagnoses (ICD codes T81.4, T81.8)",
  },
  {
    id: "HAND_HYGIENE_COMPLIANCE",
    name: "Hand Hygiene Compliance Rate",
    category: "Infection Control",
    nabhStandard: "PCI-1",
    description: "Percentage of observed hand hygiene opportunities with compliance",
    numeratorDesc: "Number of compliant hand hygiene opportunities",
    denominatorDesc: "Total hand hygiene opportunities observed",
    targetRate: 90.0,
    computationType: "manual",
    dataSource: "manual entry",
  },

  // ── Patient Safety ────────────────────────────────────────────────────
  {
    id: "FALL_RATE",
    name: "Patient Fall Rate",
    category: "Patient Safety",
    nabhStandard: "PSQ-1",
    description: "Number of patient falls per 1,000 patient-days",
    numeratorDesc: "Number of patient falls",
    denominatorDesc: "Total patient-days (×1000)",
    targetRate: 3.0,
    computationType: "semi",
    dataSource: "adverse event reports + encounter notes",
  },
  {
    id: "BED_SORE_RATE",
    name: "Hospital-Acquired Bed Sore Rate",
    category: "Patient Safety",
    nabhStandard: "PSQ-2",
    description: "Percentage of inpatients with hospital-acquired pressure ulcers",
    numeratorDesc: "Number of new pressure ulcers (stage 2+)",
    denominatorDesc: "Number of inpatients at risk",
    targetRate: 5.0,
    computationType: "semi",
    dataSource: "diagnoses (ICD codes L89.-)",
  },
  {
    id: "BLOOD_TRANSFUSION_REACTION",
    name: "Blood Transfusion Reaction Rate",
    category: "Patient Safety",
    nabhStandard: "PSQ-5",
    description: "Percentage of blood transfusions with adverse reactions",
    numeratorDesc: "Number of transfusion reactions",
    denominatorDesc: "Total blood transfusions",
    targetRate: 1.0,
    computationType: "auto",
    dataSource: "diagnoses (ICD codes T80.0-T80.9)",
  },

  // ── Operational ───────────────────────────────────────────────────────
  {
    id: "BED_OCCUPANCY",
    name: "Bed Occupancy Rate",
    category: "Operational",
    nabhStandard: "MIS-1",
    description: "Percentage of bed capacity occupied",
    numeratorDesc: "Total occupied bed-days",
    denominatorDesc: "Total available bed-days",
    targetRate: 75.0,
    computationType: "auto",
    dataSource: "encounters",
  },
  {
    id: "OT_UTILIZATION",
    name: "OT Utilization Rate",
    category: "Operational",
    nabhStandard: "MIS-2",
    description: "Percentage of scheduled OT time utilized",
    numeratorDesc: "Total OT hours utilized",
    denominatorDesc: "Total OT hours scheduled",
    targetRate: 80.0,
    computationType: "auto",
    dataSource: "encounters (OT type)",
  },
  {
    id: "LAB_TAT",
    name: "Lab Turnaround Time Compliance",
    category: "Operational",
    nabhStandard: "MIS-3",
    description: "Percentage of lab tests completed within TAT",
    numeratorDesc: "Number of tests completed within TAT",
    denominatorDesc: "Total number of lab tests",
    targetRate: 95.0,
    computationType: "auto",
    dataSource: "lab_orders",
  },
  {
    id: "ED_DOOR_TO_DOCTOR",
    name: "ED Door-to-Doctor Time Compliance",
    category: "Operational",
    nabhStandard: "MIS-4",
    description: "Percentage of ED patients seen by doctor within 30 minutes",
    numeratorDesc: "Number of ED patients seen within 30 min",
    denominatorDesc: "Total ED patients",
    targetRate: 90.0,
    computationType: "auto",
    dataSource: "encounters (Emergency type)",
  },

  // ── Patient Rights ────────────────────────────────────────────────────
  {
    id: "CONSENT_COMPLIANCE",
    name: "Consent Documentation Compliance",
    category: "Patient Rights",
    nabhStandard: "PR-1",
    description: "Percentage of procedures with documented consent",
    numeratorDesc: "Number of procedures with documented consent",
    denominatorDesc: "Total number of procedures",
    targetRate: 100.0,
    computationType: "auto",
    dataSource: "abdm consent + clinical consent records",
  },
  {
    id: "PATIENT_SATISFACTION",
    name: "Patient Satisfaction Score",
    category: "Patient Rights",
    nabhStandard: "PR-4",
    description: "Average patient satisfaction score",
    numeratorDesc: "Sum of satisfaction scores",
    denominatorDesc: "Number of responses",
    targetRate: 85.0,
    computationType: "manual",
    dataSource: "patient feedback surveys",
  },
];
